### ISSUE TITLE
Too easy to corrupt file

### ISSUE THREAD

**Issue by brian-hay** [JunoLab/atom-bombe#2]
I thought this was the answer to my prayers but just lost everything I was working on. After encrypting the plain text file and adding my text I hit CTRL + S to save, the file gets encrypted and displayed in the edit window as encrypted. But it's all too easy to hit CTRL + S again in this encrypted view, which encrypts again, and suddenly there's no easy way back to the decrypted raw text.

Other than "being careful", is there any way to avoid this?

**Comment by brian-hay** [comment]
Is it possible to add a check/fail-safe whereby save/encrypt only ever operates on the decrypted raw text, never on the cipher?

**Comment by MikeInnes** [comment]
Sorry to hear that – this must be due to a recent change in Atom's behaviour. Previously, saving the file would keep the plain-text version in place so that the encryption is transparent (as in the readme demo).

I will spend some time trying to restore the previous behaviour today.

**Comment by MikeInnes** [comment]
Pushed a new version which should fix this, let me know if you have any other issues.

Adding a safeguard in case something like this happens again would be a welcome patch if you're willing to put together a PR.

**Comment by brian-hay** [comment]
Thanks a lot Mike. I'll test it out.
