### ISSUE TITLE
Not shown when searching.

### ISSUE THREAD

**Issue by hykilpikonna** [JunoLab/atom-bombe#3]
I have Bombe v0.1.3 installed but it is not shown when I search it.
I tried restarting and reinstalling, and none of them worked.
Is it my problem? or is it just because this project is outdated?

Atom version: v1.30.0 x64

![image](https://user-images.githubusercontent.com/22280294/45599591-2aed8700-b9bc-11e8-8682-dec59da62c00.png)
![image](https://user-images.githubusercontent.com/22280294/45599592-32ad2b80-b9bc-11e8-829d-b65edf3c1a56.png)

**Comment by rafael-rodrigues** [comment]
The same here.

**Comment by klaurence** [comment]
Well, it does happen. I've found out that "Encrypt This File" and "Decrypt this File" only shows when your currently focused window is a file (like a .txt file).

**Comment by hykilpikonna** [comment]
> Well, it does happen. I've found out that "Encrypt This File" and "Decrypt this File" only shows when your currently focused window is a file (like a .txt file).

It worked when the currently focused window is a file. Thanks!
